### PR TITLE
Use play 2.4 and bump each dependency to its latest version

### PR DESCRIPTION
**Pull request by lichtsprung**

### CODE REVIEW

**Comment by magro** [comment]
Cool! :-) README mentions GlobalSettings, perhaps this might be replaced with s.th. more appropriate.

**Comment by lichtsprung** [comment]
Working on it ;)

**Comment by lichtsprung** [comment]
I will remove the scala 2.10 cross compilation target for this branch as there is no akka 2.4.x version for scala 2.10.

**Comment by lichtsprung** [comment]
The build seems to fail because of the anonymous function _ => 10 in JobUpdater(Spec). The function is instantiated two times which results in a failing check as it is apparently comparing the references of the function. 

The test doesn't fail with earlier versions of Scala 2.11 but 2.11.7 is pulled by Akka and play 2.4.x.

I will give it a try as soon as I have a working local test environment with Cassandra 2.x again...

**Pull request merged**
